### ISSUE TITLE
Add an app for a existing project

### ISSUE THREAD

**Issue by robertpro** [pinax/pinax-cli#16]
I know this is "Starter projects", but I am wondering if I can add a Pinax app for an existing project instead of creating a new one

**Comment by KatherineMichel** [comment]
@robertpro Not sure that I'm understanding your question. If you use the pinax-cli to install a starter project on your computer, as part of that, it will include a requirements.txt or pipfile that you can use to install the dependencies, including the pinax-apps that are installed within the project. If you are talking about installing a pinax-app in an existing pinax or Django project, you would probably use pip (or pipenv?) to install it, then freeze the requirements.

**Comment by KatherineMichel** [comment]
Looking back at this, no, the pinax-cli is setup to just use Pinax Starter Apps. You can fork it and create your fork it and modify it, per the MIT license. The Pinax version is fit for Pinax's purpose though. Closing issue. Sorry.

**Comment by geauxdojang** [comment]
@KatherineMichel I have an **account** app in a project, how can I add **stripe** and **blog** app to the project? Thanks.
